package MainWindow;

import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.DefaultListModel;

/**
 * This class is the GUI that is used for the Lobby.
 * It contains a list of users currently online, a section for stats to appear,
 * and also a list of invites you have available.
 * @author CashNCarry
 */
public class LobbyWindow extends javax.swing.JFrame {

  private LobbyWindowController lwc;

  /**
   * Array full of the user that are invited you
   */
  public ArrayList<String> invite = new ArrayList<String>();

  /**
   * Creates new form LobbyWindow
   * @param lwc
   */
  public LobbyWindow(LobbyWindowController lwc) {
    this.lwc = lwc;
    initComponents();
    this.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    onlineUserList = new javax.swing.JList<>();
    inviteTF = new javax.swing.JTextField();
    InviteButton = new javax.swing.JButton();
    onlineUsersLabel = new javax.swing.JLabel();
    statsLabel = new javax.swing.JLabel();
    gamesPlayedLabel = new javax.swing.JLabel();
    gamesPlayedScoreLabel = new javax.swing.JLabel();
    gamesWonLabel = new javax.swing.JLabel();
    gamesWonScoreLabel = new javax.swing.JLabel();
    gamesLostLabel = new javax.swing.JLabel();
    gamesLostScoreLabel = new javax.swing.JLabel();
    logoutButton = new javax.swing.JButton();
    jScrollPane4 = new javax.swing.JScrollPane();
    inviteUserList = new javax.swing.JList<>();
    jLabel7 = new javax.swing.JLabel();
    acceptButton = new javax.swing.JButton();
    messageLabel = new javax.swing.JLabel();
    declineButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setBounds(new java.awt.Rectangle(350, 200, 0, 0));
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    onlineUserList.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

      public int getSize() {
        return strings.length;
      }

      public String getElementAt(int i) {
        return strings[i];
      }
    });
    onlineUserList.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        onlineUserListMousePressed(evt);
      }
    });
    jScrollPane1.setViewportView(onlineUserList);

    inviteTF.setEditable(false);

    InviteButton.setBackground(new java.awt.Color(255, 255, 255));
    InviteButton.setText("Invite");
    InviteButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        InviteButtonMousePressed(evt);
      }
    });

    onlineUsersLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    onlineUsersLabel.setText("Online Users");

    statsLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    statsLabel.setText("Stats");

    gamesPlayedLabel.setText("Games Played:");

    gamesPlayedScoreLabel.setText("N/A");

    gamesWonLabel.setText("Games Won:");

    gamesWonScoreLabel.setText("N/A");

    gamesLostLabel.setText("Games Lost:");

    gamesLostScoreLabel.setText("N/A");

    logoutButton.setBackground(new java.awt.Color(255, 255, 255));
    logoutButton.setText("Logout");
    logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        logoutButtonMousePressed(evt);
      }
    });

    inviteUserList.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

      public int getSize() {
        return strings.length;
      }

      public String getElementAt(int i) {
        return strings[i];
      }
    });
    jScrollPane4.setViewportView(inviteUserList);

    jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel7.setText("Invite List");

    acceptButton.setBackground(new java.awt.Color(255, 255, 255));
    acceptButton.setText("Accept");
    acceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        acceptButtonMousePressed(evt);
      }
    });

    messageLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

    declineButton.setBackground(new java.awt.Color(255, 255, 255));
    declineButton.setText("Decline");
    declineButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        declineButtonMousePressed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(onlineUsersLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(inviteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(InviteButton))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                    .addGroup(layout.createSequentialGroup()
                                                                                            .addGap(76, 76, 76)
                                                                                            .addComponent(statsLabel))
                                                                                    .addGroup(layout.createSequentialGroup()
                                                                                            .addGap(48, 48, 48)
                                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addComponent(gamesPlayedLabel)
                                                                                                    .addComponent(gamesLostLabel)
                                                                                                    .addComponent(gamesWonLabel))))
                                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                            .addComponent(gamesLostScoreLabel)
                                                                                            .addGap(35, 35, 35))
                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                            .addComponent(gamesPlayedScoreLabel)
                                                                                            .addGap(33, 33, 33))
                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                            .addComponent(gamesWonScoreLabel)
                                                                                            .addGap(34, 34, 34)))))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGap(42, 42, 42)
                                                            .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(84, 84, 84))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(declineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addGap(13, 13, 13))))
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(19, 19, 19))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(onlineUsersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                            .addGap(5, 5, 5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(inviteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(InviteButton))
                                            .addGap(9, 9, 9))
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(declineButton)
                                                                    .addComponent(acceptButton)))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(statsLabel)
                                                            .addGap(34, 34, 34)
                                                            .addComponent(gamesPlayedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(gamesPlayedScoreLabel)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(gamesWonLabel)
                                                            .addGap(6, 6, 6)
                                                            .addComponent(gamesWonScoreLabel)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(gamesLostLabel)
                                                            .addGap(12, 12, 12)
                                                            .addComponent(gamesLostScoreLabel)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(logoutButton))))
    );

    getAccessibleContext().setAccessibleDescription("");

    pack();
  }// </editor-fold>                        
  
  /**
   * Login the user in when the login button is pressed.
   * @param evt 
   */
  private void logoutButtonMousePressed(java.awt.event.MouseEvent evt) {
    this.setVisible(false);
    lwc.send("Closing " + lwc.user.userName);
    System.exit(0);
    MasterController mw = new MasterController();
    mw.openMainWindow();
  }

  /**
   * Sends a message to a user and asks to play a game
   */
  private void InviteButtonMousePressed(java.awt.event.MouseEvent evt) {
    //Send invite to the online user
    String name = inviteTF.getText();
    if (!name.equals(lwc.user.userName)) {
      if (!invite.contains(name)) {
        lwc.send("Invite " + "\n" + name + "\n" + lwc.user.userName);
        invite.add(name);
        System.out.println(invite.toString());
        messageLabel.setText("You invited " + name);
      }
    }

  }

  /**
   * Sends a closing message to the server to remove them form online list and closes the GUI
   * @param evt 
   */
  private void formWindowClosing(java.awt.event.WindowEvent evt) {
    lwc.send("Closing " + lwc.user.userName);
    System.exit(0);
  }
  
  /**
   * Accepts the users invite to play a game
   * @param evt 
   */
  private void acceptButtonMousePressed(java.awt.event.MouseEvent evt) {
    if (inviteUserList.getSelectedValue().equals(null)) {
      return;
    }
    String name = inviteUserList.getSelectedValue();
    System.out.println(invite.toString());
    invite.remove(name);
    System.out.println(invite.toString());
    inviteList.clear();
    lwc.acceptButton(name);
    lwc.send("PlayGame " + lwc.user.userName);
  }

  /**
   * Get the stats of the user when clicked on the name
   * @param evt 
   */
  private void onlineUserListMousePressed(java.awt.event.MouseEvent evt) {
    String name = onlineUserList.getSelectedValue();
    inviteTF.setText(name);
    if (!name.contains("Guest")) {
      lwc.send("Stats: " + name + " " + lwc.user.userName);
    } else {
      gamesPlayedScoreLabel.setText("N/A");
      gamesWonScoreLabel.setText("N/A");
      gamesLostScoreLabel.setText("N/A");
    }
  }

  /**
   * Removes the invite from the lobby
   * @param evt 
   */
  private void declineButtonMousePressed(java.awt.event.MouseEvent evt) {
    String name = inviteUserList.getSelectedValue();
    inviteList.removeElement(name);
    lwc.send("Decline \n" + name + "\n" + lwc.user.userName);
  }

  /**
   * Updates the stats of the user
   * @param stats the wins and loss of the user
   */
  void updateStatsLabels(String stats) {
    Scanner statScan = new Scanner(stats);
    String stat = statScan.next();
    int wins = statScan.nextInt();
    int losses = statScan.nextInt();
    int total = wins + losses;
    gamesPlayedScoreLabel.setText("" + total);
    gamesWonScoreLabel.setText("" + wins);
    gamesLostScoreLabel.setText("" + losses);
  }

  /**
   * Adds the list model to the onlineUserList JList
   */
  public void updateOnlineList() {
    onlineUserList.setModel(OnlinelistModel);
  }

  /**
   * Adds the list model to the inviteUserList JList
   */
  public void updateInviteList() {
    inviteUserList.setModel(inviteList);
  }

  /**
   * A online list model
   */
  public DefaultListModel OnlinelistModel = new DefaultListModel();

  /**
   * A invite list model
   */
  public DefaultListModel inviteList = new DefaultListModel();
  // End of variables declaration                   

  // Variables declaration - do not modify                     
  private javax.swing.JButton InviteButton;
  private javax.swing.JButton acceptButton;
  private javax.swing.JButton declineButton;
  private javax.swing.JLabel gamesLostLabel;
  private javax.swing.JLabel gamesLostScoreLabel;
  private javax.swing.JLabel gamesPlayedLabel;
  private javax.swing.JLabel gamesPlayedScoreLabel;
  private javax.swing.JLabel gamesWonLabel;
  private javax.swing.JLabel gamesWonScoreLabel;
  private javax.swing.JTextField inviteTF;
  private javax.swing.JList<String> inviteUserList;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JButton logoutButton;
  public javax.swing.JLabel messageLabel;
  private javax.swing.JList<String> onlineUserList;
  private javax.swing.JLabel onlineUsersLabel;
  private javax.swing.JLabel statsLabel;
  // End of variables declaration                   

}
