package MainWindow;
/**
 *This class is for the GUI of the main window, the window that you are greeted
 * with when one first starts the application. You have the choice to play an
 * online game, login, register, play agaisnt an easy, medium, hard, or even evil
 * AI.
 */
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Main login and AI window of Gomoku
 */
public class MainWindow extends javax.swing.JFrame {

  public MainWindowController mwc;
  public String dropDown;

  /**
   * Creates new form MainWindow
   * @param mwc instance of the MainWindowController
   */
  public MainWindow(MainWindowController mwc) {
    initComponents();

    this.mwc = mwc;
    this.setVisible(true);
    passwordTF.setEditable(false);
    userNameTF.setEditable(false);
    errorLabel.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
  private void initComponents() {

    userNameLabel = new javax.swing.JLabel();
    passwordLabel = new javax.swing.JLabel();
    userNameTF = new javax.swing.JTextField();
    loginButton = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JSeparator();
    passwordTF = new javax.swing.JPasswordField();
    registerButton = new javax.swing.JButton();
    guestButton = new javax.swing.JButton();
    errorLabel = new javax.swing.JLabel();
    AccountQuestion = new javax.swing.JLabel();
    GameType = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("New Game");
    setBackground(new java.awt.Color(51, 51, 0));
    setBounds(new java.awt.Rectangle(500, 150, 50, 50));
    setFont(new java.awt.Font("Sitka Small", 1, 10)); // NOI18N
    setSize(new java.awt.Dimension(50, 50));
    setType(java.awt.Window.Type.POPUP);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    userNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
    userNameLabel.setText("Username");
    getContentPane().add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 25));

    passwordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
    passwordLabel.setText("Password");
    getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, 26));
    getContentPane().add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, -1));

    loginButton.setBackground(new java.awt.Color(255, 255, 255));
    loginButton.setText("Login");
    loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        loginButtonMouseClicked(evt);
      }
    });
    getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 90, -1));

    jSeparator1.setAlignmentX(1.0F);
    jSeparator1.setAlignmentY(1.0F);
    jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jSeparator1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
    getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 440, 0));

    passwordTF.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        passwordTFMouseClicked(evt);
      }
    });
    getContentPane().add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, -1));

    registerButton.setBackground(new java.awt.Color(255, 255, 255));
    registerButton.setText("Register");
    registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        registerButtonMouseClicked(evt);
      }
    });
    getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 90, -1));

    guestButton.setBackground(new java.awt.Color(255, 255, 255));
    guestButton.setText("Guest");
    guestButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        guestButtonMousePressed(evt);
      }
    });
    getContentPane().add(guestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 90, -1));

    errorLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    errorLabel.setForeground(new java.awt.Color(204, 0, 51));
    errorLabel.setText("Error:");
    getContentPane().add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

    AccountQuestion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    AccountQuestion.setText("Don't have an account?");
    getContentPane().add(AccountQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

    GameType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Choose Game Type", "Online Match", "AI - Hard", "AI - Medium", "AI - Easy", "AI - Evil"}));
    GameType.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        GameTypeActionPerformed(evt);
      }
    });
    getContentPane().add(GameType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

    jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 51, 102));
    jLabel1.setText("CashNCarry - GoMoKu");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

    pack();
  }// </editor-fold>                        

  /**
   * Login button event. Sends the user name and password to the server for
   * validation
   */
  private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {
    mwc.loginButtonListener();
  }

  /**
   * Calls the registerButton in main window controller to open the register
   * window.
   */
  private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {
    String userName = userNameTF.getText(); // 
    mwc.registerButton(userName);

  }

  /**
   * Closes the GUI and sends the closing message to the server
   * @param evt 
   */
  private void formWindowClosing(java.awt.event.WindowEvent evt) {
    String ip = null;
    try {
      ip = InetAddress.getLocalHost().toString();
    } catch (UnknownHostException ex) {
      Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
    }
    ip = ip.substring(ip.indexOf('/'));
    mwc.send("Closing " + mwc.user.userName + " " + ip);
    System.exit(0);
  }

  /**
   * Set the error to the main window GUI and makes it visible.
   * @param error name of the error
   */
  public void setError(String error) {
    errorLabel.setText(error);
    errorLabel.setVisible(true);
  }

  /**
   * Open the lobby view when the guest button is clicked.
   */
  private void guestButtonMousePressed(java.awt.event.MouseEvent evt) {
    String ip = null;
    try {
      ip = InetAddress.getLocalHost().toString();
    } catch (UnknownHostException ex) {
      Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
    }
    ip = ip.substring(ip.indexOf('/'));

    Random ran = new Random();
    int num = ran.nextInt(9999) + 1;
    String guest = "Guest" + num;

    mwc.send("Guest \n" + ip + "\n" + guest);
    mwc.user.userName = guest;
  }

  /**
   * Set the password text field to empty when clicked.
   */
  private void passwordTFMouseClicked(java.awt.event.MouseEvent evt) {
    passwordTF.setText("");
  }

  /**
   * Get what the user pick from the drop down main
   * @param evt 
   */
  private void GameTypeActionPerformed(java.awt.event.ActionEvent evt) {
    mwc.gameType();
  }

  // Variables declaration - do not modify                     
  private javax.swing.JLabel AccountQuestion;
  public javax.swing.JComboBox<String> GameType;
  private javax.swing.JLabel errorLabel;
  public javax.swing.JButton guestButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JSeparator jSeparator1;
  public javax.swing.JButton loginButton;
  private javax.swing.JLabel passwordLabel;
  public javax.swing.JPasswordField passwordTF;
  private javax.swing.JButton registerButton;
  private javax.swing.JLabel userNameLabel;
  public javax.swing.JTextField userNameTF;
  // End of variables declaration                   
}
