package MainWindow;
/**
 * This class creates a register window that is used by the user to create a 
 * username and password so they can log in again and keep track of stats and 
 * have a fun unique name.
 */
import java.awt.event.ActionEvent;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Opens a register window
 */
public class RegisterWindow extends javax.swing.JFrame {

  private RegisterWindowController rwc;
  private int flag = 0;

  /**
   * Creates new form RegisterWindowNew
   *
   * @param userName the name of the user
   * @param rwc instance of the controller
   */
  public RegisterWindow(String userName, RegisterWindowController rwc) {
    initComponents();
    registerUserNameTF.setText(userName);
    this.rwc = rwc;
    this.setVisible(true);
  }

  /**
   * Creates new form RegisterWindow
   * @param rwc reference to the RegisterWindowController
   */
  public RegisterWindow(RegisterWindowController rwc) {
    initComponents();
    this.rwc = rwc;
    this.setVisible(true);
  }

  /**
   * Set the error to the register window GUI and makes it visible.
   * @param error name of the error from the server
   */
  public void setError(String error) {
    flag = 1;
    errorLabel.setText(error);
    errorLabel.setVisible(true);
  }

  /**
   * Set the flag value to 1
   */
  public void setFlag() {
    flag = 1;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    registerUserNameTF = new javax.swing.JTextField();
    registerPasswordTF = new javax.swing.JTextField();
    registerUserNameLabel = new javax.swing.JLabel();
    registerPasswordLabel = new javax.swing.JLabel();
    errorLabel = new javax.swing.JLabel();
    registerButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Register Window");

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel1.setText("Register");

    registerUserNameTF.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
    registerUserNameTF.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        registerUserNameTFActionPerformed(evt);
      }

      private void registerUserNameTFActionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
      }
    });

    registerPasswordTF.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

    registerUserNameLabel.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
    registerUserNameLabel.setText("Username");
    registerUserNameLabel.setToolTipText("");

    registerPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
    registerPasswordLabel.setText("Password");

    errorLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

    registerButton.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
    registerButton.setText("Register");
    registerButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        registerButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGap(7, 7, 7)
                                                            .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(registerUserNameLabel)
                                                                    .addComponent(registerPasswordLabel))
                                                            .addGap(36, 36, 36)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(registerUserNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(registerPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                                            .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(80, 80, 80)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(registerUserNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(registerUserNameLabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(registerPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(registerPasswordLabel))
                                            .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(49, 49, 49)))
                            .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>                        

  /**
   * Added some conditions for the username and password that the user has to
   * meet before registering
   */
  private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {
    flag = 0;

    // no spaces in the user name
    if (registerUserNameTF.getText().contains(" ")) {
      setError("The user name you entered containse a space.");
      registerUserNameTF.setText("");
      return;
    }
    // user name has to be grater then 3 charactors 
    if (registerUserNameTF.getText().length() < 3) {
      setError("The user name you entered is too short.");
      return;
    }
    // user name has to be less the 18 charactors 
    if (registerUserNameTF.getText().length() > 18) {
      setError("The user name you entered is too long.");
      registerUserNameTF.setText(""); //Only clears TF when too long so they can try again. When too short, user info is kept so they can add more text or numbers.
      return;
    }
    // password has to be grater then 3 charactors 
    if (registerPasswordTF.getText().length() < 3) {
      setError("The password you entered is too short.");
      registerPasswordTF.setText("");
      return;
    }
    // no spaces in the password 
    if (registerPasswordTF.getText().contains(" ")) {
      setError("The password you entered contains a space.");
      registerPasswordTF.setText("");
      return;
    }

    this.rwc.send("register " + registerUserNameTF.getText() + " " + registerPasswordTF.getText());

    try {
      TimeUnit.SECONDS.sleep(1);
    } catch (InterruptedException ex) {
      Logger.getLogger(RegisterWindow.class.getName()).log(Level.SEVERE, null, ex);
    }

    if (flag == 1) {
      setError("Desired username is already taken. Try again.");
      registerUserNameTF.setText("");
      registerPasswordTF.setText("");
      return;
    }

    rwc.close();
  }

  // Variables declaration - do not modify                     
  private javax.swing.JLabel errorLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JButton registerButton;
  private javax.swing.JLabel registerPasswordLabel;
  private javax.swing.JTextField registerPasswordTF;
  private javax.swing.JLabel registerUserNameLabel;
  private javax.swing.JTextField registerUserNameTF;
  // End of variables declaration                   
}
